services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  #    DooFinderBundle\Command\TestCommand:
  #        private: false
  #        tags: ['controller.service_arguments']

  DooFinderBundle\Command\SetupDooFinderTypesCommand:
    private: false
    tags: ['controller.service_arguments']

  DooFinderBundle\Command\PushObjectsToDooFinderCommand:
    private: false
    tags: ['controller.service_arguments']

  DooFinderBundle\Command\ProcessDooFinderDataFeedCommand:
    private: false
    tags: ['controller.service_arguments']